### ISSUE TITLE
No tray icon on Windows11

### ISSUE THREAD

**Issue by dream2333** [Aetopia/NoSteamWebHelper#16]
I started the program on the latest Windows 11, but didn't find any icons in the tray bar, and CEF didn't shut down after the game started.

**Comment by Aetopia** [comment]
Can you send a screenshot of your tray menu?

**Comment by veksha** [comment]
i have tray icon on my windows 11 (10.0.22621.3155)
path to steam folder: `D:\Games\Steam\`

what is your ver and path?
(it was a bug in the past related to path length.)

**Comment by dream2333** [comment]
> i have tray icon on my windows 11 (10.0.22621.3155) path to steam folder: `D:\Games\Steam\`
> 
> what is your ver and path? (it was a bug in the past related to path length.)

win11(10.0.22631)
My steam floder path : C:\Program Files (x86)\Steam

**Comment by Aetopia** [comment]
I finally got to know what's preventing the NoSteamWebHelper from functioning properly.

```c
if (CompareStringOrdinal(L"vguiPopupWindow", -1, szClassName, -1, FALSE) != CSTR_EQUAL ||
    CompareStringOrdinal(L"Untitled", -1, szString, -1, FALSE) != CSTR_EQUAL)
    return;
```
To detect if Steam has fully initialized, NoSteamWebHelper waits for a window with the class name of `vguiPopupWindow` and title of `Untitled` to spawn.

Someone reported the same issue on Discord, you were having @dream2333.

![image](https://github.com/Aetopia/NoSteamWebHelper/assets/41850963/96875eeb-2ec8-424c-abca-d6d940f35e58)

It seems changes the window title name based on what language, you are currently using in Windows.
Since Steam creates multiple windows with the class name of `vguiPopupWindow` but only one with a title.

The program just checks if there a non-null title.
```c
if (CompareStringOrdinal(L"vguiPopupWindow", -1, szClassName, -1, FALSE) != CSTR_EQUAL ||
    GetWindowTextLengthW(hwnd) < 1)
    return;
```

**Comment by Aetopia** [comment]
Please try using [v4.1.2](https://github.com/Aetopia/NoSteamWebHelper/releases/tag/v4.1.2)

**Comment by GogoVang** [comment]
Had the same problem as the OP, v4.1.2 fixed this. Huge thank you.

**Comment by Aetopia** [comment]
Fixed 👍🏼.

**Comment by Aetopia** [comment]
> > Fixed 👍🏼.
> 
> Does not work!

Please make a new issue for this!

**Comment by liliill** [comment]
I have solved the problem once and for all, create a batch file and add it there!

@echo off
taskkill /f /im steam.exe
start "" "c:/program files (x86)/steam\steam.exe" -dev -console -nofriendsui -no-dwrite -nointro -nobigpicture -nofasthtml -nocrashmonitor -noshaders -no-shared-textures -disablehighdpi -cef-single-process -cef-in-process-gpu -single_core -cef-disable-d3d11 -cef-disable-sandbox -disable-winh264 -no-cef-sandbox -vrdisable -cef-disable-breakpad
